<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BhushanPatil" failures="2" tests="4" name="Test" time="1.104" errors="0" timestamp="2023-07-28T12:53:59 IST">
  <testcase classname="ITestListener.ITestListenerWithExample" name="TestFailed" time="1.018">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method ITestListener.ITestListenerWithExample.TestFailed() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method ITestListener.ITestListenerWithExample.TestFailed() didn't finish within the time-out 1000
at java.base@11.0.18/java.lang.Thread.sleep(Native Method)
at app//ITestListener.ITestListenerWithExample.TestFailed(ITestListenerWithExample.java:19)
at java.base@11.0.18/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.18/java.lang.Thread.run(Thread.java:834)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- TestFailed -->
  <testcase classname="ITestListener.ITestListenerWithExample" name="TestFailed1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ITestListener.ITestListenerWithExample.TestFailed1(ITestListenerWithExample.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestFailed1 -->
  <testcase classname="ITestListener.ITestListenerWithExample" name="TestPassed" time="0.0"/>
  <testcase classname="ITestListener.ITestListenerWithExample" name="TestSkipped" time="0.0">
    <skipped/>
  </testcase> <!-- TestSkipped -->
</testsuite> <!-- Test -->
